Update MLX single user deployment page
machine-learning-exchange/mlx pull request #146
Opened 2021-07-14 21:27 UTC by Tomcli

Update MLX single user deployment page to include delete instructions and move the Read-only mode to a hidden readme.

Note: For datashim there's no official release, so we will be using the latest images at the moment.

2021-07-14 22:36 UTC, ckadner requested changes
Thanks @Tomcli -- I just have a few wording change recommendations

2021-07-14 22:36 UTC, ckadner commented on docs/mlx-setup.md
> +This MLX contains:
"This MLX deployment includes"

2021-07-14 22:36 UTC, ckadner commented on docs/mlx-setup.md
> +This MLX contains:
should we make those bullets links to their respective repos/docs?

2021-07-14 22:36 UTC, ckadner commented on docs/mlx-setup.md
> +We will be using [kustomize 3.2.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0) to align with Kubeflow's requirements because we will be also install kubeflow components as part
"We **are** using" ... "because we will install" ...

2021-07-14 22:36 UTC, ckadner commented on docs/mlx-read-only-deployment.md
> +## Deploy the MLX ReadOnly mode on an Existing Kubernetes Cluster
"read-only" instead of "ReadOnly"

2021-07-14 22:36 UTC, ckadner commented on docs/mlx-read-only-deployment.md
> +To deploy the minimum MLX on an existing Kubernetes Cluster, we can clone the MLX manifests and deploy it with Kustomize. The minimum MLX is only for Read only. To deploy the MLX ReadOnly mode on an
I think this can be shortened to:

```
To deploy MLX in read-only mode on an existing Kubernetes cluster without Kubeflow, clone the MLX repo and apply the manifest using Kustomize:
```

2021-07-14 22:36 UTC, ckadner commented on docs/mlx-read-only-deployment.md
> +This MLX ReadOnly mode only contains MLX ReadOnly deployment.
this should be redundant

2021-07-14 23:42 UTC, Tomcli commented
thanks @ckadner I addressed your comments

2021-07-15 02:49 UTC, ckadner approved these changes
Thanks @Tomcli looks good

I will give @animeshsingh a chance to review as well

2021-07-15 23:36 UTC, ckadner commented
@animeshsingh -- if you have no further comments/revisions, I will `lgtm` this tonight

2021-07-16 19:40 UTC, animeshsingh commented on docs/mlx-setup.md
> +## Deploy the MLX Stack on an Existing Kubernetes Cluster
```suggestion
# Deploy MLX on an existing Kubernetes cluster

## Prerequisites
* An existing Kubernetes cluster. Version 1.17+
* The minimum recommended capacity requirement for MLX is 8 vCPUs and 16GB RAM
* If you are using IBM Cloud, follow the appropriate instructions for standing up your Kubernetes cluster using [IBM Cloud Public](https://cloud.ibm.com/docs/containers?topic=containers-cs_cluster_tutorial#cs_cluster_tutorial)
* If you are using OpenShift on IBM Cloud, please follow the instructions for standing up your [IBM Cloud Red Hat OpenShift cluster](https://cloud.ibm.com/docs/containers?topic=containers-openshift_tutorial)
* [`kustomize v3.0+`](https://kubernetes-sigs.github.io/kustomize/installation/) is installed
```

2021-07-16 19:40 UTC, animeshsingh commented on docs/mlx-setup.md
> +To deploy the MLX single user mode on an existing Kubernetes Cluster, we can clone the MLX manifests and deploy it with Kustomize. This MLX deployment doesn't include model serving with KFServing. To
```suggestion
To deploy the MLX single user mode on an existing Kubernetes Cluster, clone the MLX manifests and deploy it with Kustomize. 
```

2021-07-16 19:40 UTC, animeshsingh commented on docs/mlx-setup.md
> +We are using [kustomize 3.2.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0) to align with Kubeflow's requirements because we will install kubeflow components as part of this MLX
```suggestion
This MLX deployment doesn't include model serving with KFServing. To experience the other MLX features such as KFServing, multi-user mode, and Istio mutual TLS, please install the extra plugins by following the instructions on [deploying it on an existing Kubeflow](/docs/install-mlx-on-kubeflow.md#deploy-mlx-on-an-existing-kubeflow-cluster).
```

2021-07-16 21:27 UTC, ckadner approved these changes
/lgtm

Thanks @Tomcli and @animeshsingh

2021-07-16 21:30 UTC, merged