update single/multi-user deployment instructions
machine-learning-exchange/mlx pull request #154
Opened 2021-07-16 21:48 UTC by animeshsingh

further update the instructions to clarify

2021-07-17 05:58 UTC, ckadner requested changes
@animesh - since we are rewording, I have a few more nit picks _above_ ;-)

2021-07-17 05:58 UTC, ckadner commented on docs/install-mlx-on-kubeflow.md
> +This is a full blown deployment which includes all the MLX components like
how about "complete" instead of "full blown"

2021-07-17 05:58 UTC, ckadner commented on docs/mlx-setup.md
> +Above MLX deployment doesn't include:
"This" instead of "Above"

2021-07-17 05:58 UTC, ckadner commented on docs/mlx-setup.md
> +To get the above features please install the extra plugins by following the instructions for [MLX deployment an existing Kubeflow cluster](/docs/install-mlx-on-kubeflow.md#deploy-mlx-on-an-existing-k
"These" instead of "above"

2021-07-17 05:58 UTC, ckadner commented on docs/install-mlx-on-kubeflow.md
> +- Multi-User mode
should we add links to the _above_ projects?

2021-07-17 05:58 UTC, ckadner commented on docs/install-mlx-on-kubeflow.md
> +For above, we deploy MLX on a Kubernetes cluster which has an existing Kubeflow 1.3.0 installed. We can simply use the kustomize plugin that comes with `kubectl` client on v1.17+. Clone the [MLX](htt
replace:
> "For above, we deploy MLX on a Kubernetes cluster which has an existing Kubeflow 1.3.0 installed. We can simply use the kustomize plugin that comes with"

with:
> "To deploy MLX on a Kubernetes cluster which has Kubeflow 1.3.0 already installed, we use the `kustomize` plugin that comes with ..."

2021-07-19 17:32 UTC, ckadner approved these changes

2021-07-19 17:34 UTC, ckadner commented
@animeshsingh -- I made a few revisions as outlined in my review suggestions

2021-07-20 21:04 UTC, Tomcli commented on docs/mlx-setup.md
> +To delete the this MLX deployment, run the following commands in the same manifests folder.
```suggestion
To delete this MLX deployment, run the following commands in the same manifests folder.
```

2021-07-20 21:04 UTC, Tomcli commented
/lgtm

2021-07-20 21:09 UTC, merged