Add GitHub actions to build UI and API images
machine-learning-exchange/mlx pull request #174
Opened 2021-08-03 23:33 UTC by Tomcli

UI and API images will be pushed on every new commit to `main` branch after this PR.

2021-08-03 23:36 UTC, Tomcli commented
/assign @ckadner

2021-08-03 23:37 UTC, ckadner requested changes
Thanks @Tomcli -- looks good other than the copy-pasted `name` ;-)

2021-08-03 23:37 UTC, ckadner commented on .github/workflows/mlx-ci.yml
> +name: KFP Tekton Unit Tests
```YAML
name: "Build MLX API and UI images"
```

2021-08-03 23:37 UTC, Tomcli commented
FYI Only commits to the `main` branch will trigger the jobs with `github.event_name == 'push'`, so jobs in the PR will not push to the dockerhub repo.

2021-08-03 23:39 UTC, Tomcli commented on .github/workflows/mlx-ci.yml
> +name: KFP Tekton Unit Tests
thanks, fixed it.

2021-08-03 23:41 UTC, ckadner approved these changes
/lgtm

2021-08-03 23:41 UTC, Tomcli commented
Example push job in my fork https://github.com/Tomcli/mlx/runs/3236092498?check_suite_focus=true

2021-08-04 00:04 UTC, Tomcli commented
Looks like the github API doesn't like my commits. Let me force push the history.

2021-08-04 00:18 UTC, Tomcli commented
Ok this is the glitch from the tide code, need to close and reopen PR.

2021-08-04 00:20 UTC, Tomcli commented
/reopen

2021-08-04 00:20 UTC, Tomcli commented
/open

2021-08-04 00:21 UTC, Tomcli commented
/close

2021-08-04 00:21 UTC, Tomcli commented
/open

2021-08-04 00:21 UTC, Tomcli commented
/reopen

2021-08-04 00:23 UTC, Tomcli commented
There's some caching glitch in tide. I will manually merge only for this time.

2021-08-04 00:23 UTC, merged