Add max/dax description in details page
machine-learning-exchange/mlx pull request #179
Opened 2021-08-12 01:22 UTC by drewbutlerbb4

Add max/dax description in details page which pulls from a markdown file specified by a metadata component.

2021-08-12 16:50 UTC, yhwang commented on dashboard/origin-mlx/src/components/MarkdownViewer.tsx
> +      fetch("https://raw.githubusercontent.com/IBM/MAX-Object-Detector/master/README.md").then((response) => response.text()).then((text) => {
nit: I guess this is for POC and the uri would be passed in from somewhere, right? so maybe it could be a property and use constant value for now.

2021-08-12 16:51 UTC, yhwang approved these changes

2021-08-12 17:07 UTC, yhwang commented
when viewing the code, I thought about one thing:
is it possible to have a `BaseDetail` class and other detail (ModelDetail, DatasetDetail) components inherit from it?
not very familiar with ReactJS, just wondering in this case, maybe you don't need to update similar change in multiple detail components.

2021-08-12 17:19 UTC, drewbutlerbb4 commented on dashboard/origin-mlx/src/components/MarkdownViewer.tsx
> +      fetch("https://raw.githubusercontent.com/IBM/MAX-Object-Detector/master/README.md").then((response) => response.text()).then((text) => {
Yes, a new metadata portion needs to be devised and added into the MLX yaml's. Once @ckadner has added this, I will rebase the PR and derive the url from the yaml. For now the PR will be `do-not-merge/work-in-progress` until the url is added to the yaml.

2021-08-12 17:24 UTC, drewbutlerbb4 commented
> when viewing the code, I thought about one thing:
> is it possible to have a `BaseDetail` class and other detail (ModelDetail, DatasetDetail) components inherit from it?
> not very familiar with ReactJS, just wondering in this case, maybe you don't need to update similar change in multiple detail components.

Yes this could be done, but the Details (ModelDetail, DatasetDetail) has been the component which changes the most frequently so it did not beneficial in the past. I do agree that some `BaseDetail` class could be made which provides the tab/content control functionality and ModelDetail/DatasetDetail/... could specify what the tab names/ contents are.

2021-08-12 17:35 UTC, yhwang commented
that thought just came to my mind when reviewing your change. I don't know if it's applicable for those Details components or not. I guess you know those components the most and should be food for thought to you.

2021-08-12 18:14 UTC, ckadner commented
Thanks @drewbutlerbb4 -- could you throw a screenshot into the PR description? :-)

Do you need the `readme_url` to be part of the asset properties or do you want to parse that field out of the YAML?

Regarding a "`BaseDetail`" class, the API has an equivalent `ApiAsset` base class which captures all of the properties which are common to all asset types:
https://github.com/machine-learning-exchange/mlx/blob/2fb61a8840696c7ede77cd600caa8922178ec8b0/api/swagger/swagger.yaml#L2091-L2114

2021-08-12 20:54 UTC, ckadner requested changes
Thanks @drewbutlerbb4 -- could you throw a screenshot into the PR description? :-)

Do you need the `readme_url` to be part of the asset properties or do you (MLX UI) want to parse that field out of the YAML? If the UI parses it out of the YAML, then no API involvement is needed. Do you want to add the `readme_url` field to some of the model and dataset YAMLs in the [katalog](https://github.com/machine-learning-exchange/katalog/) repo. And temporarily link it to the public READMEs for MAX models found [here](https://github.com/orgs/IBM/repositories?q=MAX). For DAX datasets, you could create one or two in the katalog repo based on the internal READMEs pointed out by @kmh4321 

Regarding a "`BaseDetail`" class, the API has an equivalent `ApiAsset` base class which captures all of the properties which are common to all asset types:
https://github.com/machine-learning-exchange/mlx/blob/2fb61a8840696c7ede77cd600caa8922178ec8b0/api/swagger/swagger.yaml#L2091-L2114

2021-08-16 15:40 UTC, drewbutlerbb4 commented
<img width="1680" alt="Screen Shot 2021-08-16 at 8 35 39 AM" src="https://user-images.githubusercontent.com/32145094/129590560-a717e8b8-7291-42d6-ace2-056b6c278d64.png">

@ckadner Here is a screenshot and [here](https://github.com/machine-learning-exchange/katalog/pull/15#issuecomment-898766422) is the katalog PR.

2021-08-17 07:21 UTC, ckadner commented
Thanks @drewbutlerbb4 -- only a small change needed on your katalog PR. Otherwise looks good!

👍🏻

2021-08-17 07:21 UTC, ckadner approved these changes

2021-08-17 23:50 UTC, ckadner approved these changes
/lgtm

2021-08-17 23:58 UTC, merged