Remove detail tab and update formatting
machine-learning-exchange/mlx pull request #195
Opened 2021-08-31 21:42 UTC by drewbutlerbb4

Signed-off-by: Andrew-Butler <Andrew.Butler@ibm.com>

@ckadner As mentioned in the meeting today
<img width="1678" alt="Screen Shot 2021-08-31 at 2 24 27 PM" src="https://user-images.githubusercontent.com/32145094/131577802-285aaa75-133a-4b33-92c4-3a380166a008.png">

2021-08-31 22:01 UTC, drewbutlerbb4 commented
@ckadner @Tomcli is this just flaky tests? Says the API failed to build, but nothing has been changed.

2021-08-31 23:04 UTC, ckadner commented
> @ckadner @Tomcli is this just flaky tests? Says the API failed to build, but nothing has been changed.

This kind of error can happen when thirdparty libraries get update. Will take me a while to solve. Ignore it for the time being.

2021-08-31 23:07 UTC, ckadner commented
In your screenshot, the "🏠 **Home**" tab is illuminated in the navigation, but the content shows a dataset?

2021-08-31 23:11 UTC, ckadner requested changes

2021-08-31 23:11 UTC, ckadner commented on dashboard/origin-mlx/src/styles/Models.css
> +  padding-left: 10px;
looks better with some space, but I think we can go bigger. How does 30px look? I think Github gives READMEs 32 px which looks nice.

2021-09-01 17:42 UTC, drewbutlerbb4 commented
@ckadner Here is 30px:
<img width="1680" alt="Screen Shot 2021-09-01 at 10 41 35 AM" src="https://user-images.githubusercontent.com/32145094/131718356-0d581dd6-b38e-410c-8aee-b99f8da1c2dc.png">

2021-09-01 17:48 UTC, ckadner approved these changes
/lgtm

Thanks @drewbutlerbb4

2021-09-01 17:49 UTC, drewbutlerbb4 commented
/hold

2021-09-01 17:49 UTC, merged

2021-09-01 17:51 UTC, drewbutlerbb4 commented
@ckadner 
Well I tried to stop the merging process haha, I hadn't added the 30px in a commit yet. Just showed a picture. I can add it to a separate PR right now if you want it for the gifs?

2021-09-01 17:52 UTC, ckadner commented
> @ckadner
> Well I tried to stop the merging process haha, I hadn't added the 30px in a commit yet. Just showed a picture. I can add it to a separate PR right now if you want it for the gifs?

Yes. Please :-)

2021-09-01 18:08 UTC, ckadner commented
Follow-up PR to add the extra padding: #196

2021-09-01 18:20 UTC, ckadner commented
> @ckadner @Tomcli is this just flaky tests? Says the API failed to build, but nothing has been changed.

#197