Small navigation improvements
machine-learning-exchange/mlx pull request #238
Opened 2021-10-16 17:09 UTC by Prasantacharya

Resolves #198 
For non-logged in users, the "join the conversation" button sits at the bottom, but for admins, it is in its usual spot
Also the text now aligns with the paragraph instead of the icon

2021-10-19 20:47 UTC, Prasantacharya commented
@ckadner ive shifted down the icons a bit. Altho when i built the site to test, I didnt have the white pullet points, which I assume is what I would be centering with?

2021-10-19 23:38 UTC, ckadner commented
The speech bubble icon is aligned nicely now, but now the bullet point is sitting too low. 

<img width="266" alt="Screen Shot 2021-10-19 at 4 32 32 PM" src="https://user-images.githubusercontent.com/12246093/138004730-77570578-b943-46cd-b9e6-a037f85b4f00.png">

2021-10-19 23:40 UTC, ckadner commented
@Prasantacharya -- could you sign your commits to get the DCO check to pass?

2021-12-02 17:59 UTC, ckadner commented
@Prasantacharya -- did you ever get a chance to find out why the bullet point shows up out of line? I [screenshoted](https://github.com/machine-learning-exchange/mlx/pull/238#issuecomment-947185965) that on Firefox

2021-12-02 20:18 UTC, ckadner requested changes
@Prasantacharya -- if you can find out how to vertically align (center) the icon and text with the bullet point that would be great.

2021-12-03 19:14 UTC, Prasantacharya commented
![image](https://user-images.githubusercontent.com/23312333/144659796-61618d66-e6ee-4c63-8cc2-351f96d5dba2.png)
this is the closest ive gotten it to, does this look right?

2021-12-09 00:36 UTC, ckadner commented
> ![image](https://user-images.githubusercontent.com/23312333/144659796-61618d66-e6ee-4c63-8cc2-351f96d5dba2.png) this is the closest ive gotten it to, does this look right?

Yeah, did this require further code changes? Did you push those to this PR?

2021-12-09 00:37 UTC, ckadner commented on README.md
> +For more details about the project please follow this [announcement blog post](https://lfaidata.foundation/blog/2021/09/28/machine-learning-exchange-mlx/).
This change here seems unrelated. Could you rebase your PR or merge in the latest changes from `main`?

2021-12-10 00:14 UTC, merged

2021-12-10 00:15 UTC, ckadner reviewed
/lgtm

Thanks @Prasantacharya