Added buttons that can delete assets
machine-learning-exchange/mlx pull request #267
Opened 2021-11-29 21:28 UTC by Zachary-Fernandes

The UI now includes buttons when accessing all the assets. These
buttons delete the assets they are associated with when they are
clicked.

Resolves #157

@ckadner

2021-11-30 17:23 UTC, ckadner commented
Thank you @Zachary-Fernandes -- could you add a screenshot as well?

2021-12-01 19:00 UTC, Zachary-Fernandes commented
Sure thing, I can demonstrate it by deleting Project CodeNet Language Classifier.

Here it is before deleting:
![beforedelete](https://user-images.githubusercontent.com/32844805/144296613-16c1536a-25ad-4737-950f-235ef7a05619.PNG)

Here it is after deleting:
![afterdelete](https://user-images.githubusercontent.com/32844805/144296628-6deefbf7-5c43-414b-8c3b-ebf75a02e47f.PNG)

2021-12-02 00:21 UTC, ckadner requested changes
Thanks @Zachary-Fernandes -- just a few nit-picks ;-)

2021-12-02 00:21 UTC, ckadner commented on dashboard/origin-mlx/src/pages/MetaAllPage.tsx
> +                      <span className="delete-button-text">DELETE</span>
I would make it Title-case: `Delete`, and update the  `className="delete-button-text"` to a color and font that matches the rest of this page

2021-12-02 00:21 UTC, ckadner commented on dashboard/origin-mlx/src/pages/MetaAllPage.tsx
> +    { id: 'del', label: 'Delete Asset', numeric: false },
just `'Delete'` is enough

2021-12-09 03:41 UTC, ckadner commented
@Zachary-Fernandes does this screenshot reflect your latest changes?

<img width="934" alt="image" src="https://user-images.githubusercontent.com/12246093/145330361-d6499d5d-46d4-46c4-8a08-21b697f0c18e.png">

2021-12-09 22:46 UTC, Zachary-Fernandes commented
Yes. It originally was red with a minus sign because I could not figure out how to spawn lowercase text, but after making a new style in Models.css, I figured out how to do this.

2021-12-09 23:52 UTC, ckadner approved these changes
/lgtm

Thank you @Zachary-Fernandes

2021-12-09 23:53 UTC, merged