[WIP] Added validate-id to __init__.py
machine-learning-exchange/mlx pull request #273
Opened 2021-12-01 22:31 UTC by JAulet

Added function to validate ids of assets uploaded.
Resolves #209 
Signed-off-by: JAulet <51500017+JAulet@users.noreply.github.com>

@ckadner Please Review

2022-02-15 22:51 UTC, ckadner requested changes
Thanks @JAulet -- the original problem was not that the `id` we generate was invalid, but the `id` field inside the YAML could still be invalid. And since that YAML itself was used by another component to get the `id` the DataShim logic failed. So this PR should add some code to verify the `id`s in the YAML adhere to the k8s identifier format.

2022-02-15 22:51 UTC, ckadner commented on api/server/swagger_server/controllers_impl/notebook_service_controller_impl.py
> +    errors, status = validate_id(notebook_id)
let's move this check above line 391 where we generate the `notebook_id` and validate the `yaml_dict.get("id")`

2022-02-15 22:51 UTC, ckadner commented on api/server/swagger_server/controllers_impl/model_service_controller_impl.py
> +    errors, status = validate_id(api_model.id)
let's move this check to line 375 after we load the yaml and before we create the `ApiModel` object and validate the `model_def.get("model_identifier")`

2022-02-15 22:51 UTC, ckadner commented on api/server/swagger_server/controllers_impl/dataset_service_controller_impl.py
> +    errors, status = validate_id(dataset_id)
let's move this check above line 366after we load the YAML and before we generate the `dataset_id` and validate the `yaml_dict.get("id")`

2022-02-18 21:38 UTC, JAulet commented
@ckadner Please Review.

2022-02-18 23:14 UTC, ckadner commented
> @ckadner Please Review.

@JAulet -- did you try this out by uploading a model, dataset, notebook YAML with invalid ID values?

2022-02-22 00:58 UTC, JAulet commented
> > @ckadner Please Review.
> 
> @JAulet -- did you try this out by uploading a model, dataset, and notebook YAML respectively with invalid ID values (and with valid ones)?

Yes, I did. I got the correct output for each.

2022-02-24 18:48 UTC, ckadner approved these changes
/lgtm

Thanks @JAulet

2022-02-24 18:49 UTC, merged