Fix link and curl cmd
machine-learning-exchange/mlx pull request #294
Opened 2022-02-08 02:16 UTC by rafvasq

Updates Openshift link and fixes curl command for Kustomize installation.

Resolves #293

2022-02-08 19:51 UTC, ckadner requested changes
Thanks @rafvasq for finding and fixing the broken link and curl command.

I just have a small nit-pick :-)

2022-02-08 19:51 UTC, ckadner commented on docs/mlx-setup.md
> +* If you are using IBM Cloud, follow the appropriate instructions for standing up your Kubernetes cluster using [Kubernetes Service](https://cloud.ibm.com/docs/containers?topic=containers-cs_cluster_
... using the [IBM Cloud Kubernetes Service](https://...

2022-02-08 19:51 UTC, ckadner commented on docs/mlx-setup.md
> +   curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_{$OS}_amd64 --output kustomize
👍🏻

2022-02-09 00:20 UTC, ckadner requested changes
Thanks Rafael. Sorry, I did not look at your second change carefully earlier.

2022-02-09 00:20 UTC, ckadner commented on docs/mlx-setup.md
> +   curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_{$OS}_amd64 --output kustomize
On second look, I don't think this change is right, even though `curl` seems to work with either command variation.

https://stackoverflow.com/questions/4181703/how-to-concatenate-string-variables-in-bash/4181721#4181721

This form `_{$OS}_` prints the URL with braces "`_{Darwin}_`":
```Bash
$ echo "https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_{$OS}_amd64"

https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_{Darwin}_amd64

```

The original format (`_${OS}_`) prints the URL correctly ( "`_Darwin_`"  without braces):
```Bash
$ echo "https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_${OS}_amd64"

https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_Darwin_amd64

```

2022-02-09 03:13 UTC, rafvasq commented on docs/mlx-setup.md
> +   curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_{$OS}_amd64 --output kustomize
Thanks for looking into it. I was having issues with the original curl command and now realize that it wasn't working for me because I'm using `oh-my-zsh`, which [escapes characters with backslash when I paste a URL](https://stackoverflow.com/questions/25614613/how-to-disable-zsh-substitution-autocomplete-with-url-and-backslashes).

2022-02-09 18:14 UTC, ckadner approved these changes
/lgtm

Thanks Rafael

2022-02-09 18:15 UTC, merged

2022-02-09 18:16 UTC, ckadner commented
/assign @rafvasq