Self-Referential Links Fix for Markdown View
machine-learning-exchange/mlx pull request #306
Opened 2022-02-23 03:23 UTC by RRM123

Upgraded / Added the following dependencies to `dashboard/origin-mlx/package.json`:
`react-markdown`: ^4.0.8 ---> ^8.0.0
`remark-gfm` : ^2.0.0 ---> ^3.0.0
`rehype-slug` : ^5.0.1
`typescript-logging` : ^1.0.0

Changes were made to `OperatorDetail.tsx`, `MarkdownViewer.tsx`, and `MetaCard.tsx` to 
accommodate the new version of `react-markdown` and `rehype-slug`.

Resolves #261

Signed-off-by: RRM123 <rithikmamidi@gmail.com>
@ckadner

2022-02-24 18:22 UTC, BluThaitanium commented
Awesome work! /lgtm

2022-02-24 18:45 UTC, ckadner requested changes
Thanks @RRM123 -- looks good. Just a small question.

2022-02-24 18:45 UTC, ckadner commented on dashboard/origin-mlx/package.json
> +    "typescript-logging": "^1.0.0",
I assume you added the `typescript-logging` dependency to help with debugging, but you removed any logging statements from the code in your PR. Did the logging not work well or did you find it was not necessary given other means of debugging?

2022-02-25 00:47 UTC, ckadner commented on dashboard/origin-mlx/src/pages/MetaFeaturedPage/MetaCard.tsx
> -                  link: ({children}) => children
FYI, this link transformation rule did not seem to do anything, so we should be okay removing it, or, commenting it out to keep for future reference

2022-02-25 22:34 UTC, ckadner commented on dashboard/origin-mlx/package.json
> +    "typescript-logging": "^1.0.0",
I updated the `package.json` file to remove the `typescript-logging` dependency. 

I also regenerated the `package-lock.json` as the one you generated did not look right. Are you using an old version of NodeJS/`npm`?

2022-02-25 23:30 UTC, ckadner approved these changes
/lgtm

2022-02-25 23:31 UTC, merged