Added a script that can update the docs table
machine-learning-exchange/mlx pull request #317
Opened 2022-03-18 00:34 UTC by rafvasq

Addresses #316

Script goes into each doc and takes its first line (assumed to be a descriptive header) as a description for the documentation overview table in the /docs/ README.

It's possible that this PR makes #314 no longer needed.

FYI @ckadner

2022-03-18 23:06 UTC, ckadner requested changes
Great! Thanks @rafvasq -- I merged your other PR and merged the changes into this PR

I have only a few small nit-picks

2022-03-18 23:06 UTC, ckadner commented on tools/python/update_doc_table.py
> +def find_md_files() -> [str]:
needs one more empty line above

2022-03-18 23:06 UTC, ckadner commented on tools/python/update_doc_table.py
> +        "Documentation | Description\n"
change `Documentation` to `Document`

2022-03-18 23:06 UTC, ckadner commented on tools/python/update_doc_table.py
> +        "-----|----"
Use three hyphens in each column `| --- | --- |`

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

2022-03-18 23:06 UTC, ckadner commented on tools/python/update_doc_table.py
> +            f"{md_filenames[i]} | {descriptions[i]}"
each row in Github flavored markdown tables should start and end with a pipe character `|`

```

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

2022-03-18 23:06 UTC, ckadner commented on tools/python/update_doc_table.py
> +    table.append(
add one empty line above the table

2022-03-23 18:05 UTC, rafvasq commented on tools/python/update_doc_table.py
> +        "<!-- Do not edit. This file was generated by ./tools/python/update_doc_table.py (make update_doc_table) -->\n"
Add newline line 70

2022-03-30 08:14 UTC, ckadner requested changes
Hi Rafal, 

please change your script to use relative links instead of linking to the MLX Github repo?

Otherwise looks good.

2022-03-30 08:14 UTC, ckadner commented on docs/README.md
> +!-- Do not edit. This file was generated by ./tools/python/update_doc_table.py (make update_doc_table) -->
missing `<` at the beginning of the line

2022-03-30 08:14 UTC, ckadner commented on docs/README.md
> +!-- Do not edit. This file was generated by ./tools/python/update_doc_table.py (make update_doc_table) -->
your script does generate it correctly, btw :-)

2022-03-30 08:14 UTC, ckadner commented on docs/README.md
> +| [import-assets.md](https://github.com/machine-learning-exchange/mlx/blob/master/docs/import-assets.md) | Import Data and AI Assets in MLX Catalog |
the links here should be relative, not absolute

2022-03-30 08:14 UTC, ckadner commented on tools/python/update_doc_table.py
> +    md_filenames = ["[" + split(file)[1] + "](" + github_repo_master_path + split(file)[1] + ")"
we want relative links here

2022-03-30 18:26 UTC, ckadner requested changes
Thanks @rafvasq -- we need a little more cleanup after removing the GitHub repo links :-)

2022-03-30 18:26 UTC, ckadner commented on tools/python/update_doc_table.py
> +GITHUB_REPO = env.get(
I think the `GITHUB_REPO` constant can be removed

2022-03-30 18:26 UTC, ckadner commented on tools/python/update_doc_table.py
> +github_repo_master_path = "{}/blob/master/docs/".format(
`github_repo_master_path` is no longer needed

2022-03-30 18:26 UTC, ckadner commented on tools/python/update_doc_table.py
> +from os import environ as env
this will be an unused import after removing the `GITHUB_REPO` constant below

2022-03-30 18:26 UTC, ckadner commented on tools/python/update_doc_table.py
> +
maybe add a brief comment here to describe what the script does? something along the lines of

> This script is used to (re)generate the /docs/README.md file with a table that describes the purpose of each document. Run it from the project root folder via `make  update_doc_table`.

2022-03-30 19:43 UTC, rafvasq commented
Thanks for the reviews @ckadner, going keep a better eye out to catch theses smaller changes next time. :)

2022-03-30 20:15 UTC, ckadner approved these changes
Thanks Rafael. Looks good! :-)

2022-03-30 20:17 UTC, ckadner approved these changes

2022-03-30 20:22 UTC, merged

2022-03-30 20:23 UTC, ckadner commented
/lgtm