Consolidate UI developer docs (#258)
machine-learning-exchange/mlx pull request #323
Opened 2022-03-29 01:48 UTC by RRM123

- Deleted portion of developer-guide.md that was functionally the same as the `dashboard/origin-mlx/README.md`. Replaced with pointer to `dashboard/origin-mlx/README.md`.
- Included information about how to start the UI using an existing docker image or local code (via `npm start`).
- Included a pointer to `dashboard/origin-mlx/developer-guide.md` for Development Guidlines.
- Removed outdated `OLD_README.md`

2022-03-29 20:15 UTC, RRM123 commented
@ckadner Forgot to tag you in this PR

2022-03-30 22:32 UTC, ckadner requested changes
Thanks @RRM123 -- this is a good improvement. I would make a few small changes.

2022-03-30 22:32 UTC, ckadner commented on dashboard/origin-mlx/README.md
> +For information on how to get started with Docker Compose, and it's appropriate setup, check out the
This is a good bit of information :-)  I would change it slightly to:

> For information on how to get started with Docker Compose before making any changes to the UI code, check out the [Quick Start Guide](../../quickstart/README.md) and take a look at the [docker-compose.yaml](../../quickstart/docker-compose.yaml) file to understand how the individual services like `mysql`, `minio`, `mlx-api`, `mlx-ui`, etc. are working together.

2022-03-30 22:32 UTC, ckadner commented on dashboard/origin-mlx/README.md
> +To bring up the Docker Compose stack run:
I would remove the 2 commands here as they are duplicated from in the Quickstart guide, or, point out how they are different (i.e. using the `--project-name ...` flag)

2022-03-30 22:32 UTC, ckadner commented on dashboard/origin-mlx/README.md
> +To bring up the stack without the UI run:
these 2 commands are described already in context of the next passage

2022-04-04 23:41 UTC, RRM123 reviewed
Implemented changes outlined in the PR review.

2022-04-08 23:43 UTC, ckadner requested changes
Thank you @RRM123 -- this is a good improvement to our UI developer docs. I think we can take it a few steps further even.

2022-04-08 23:43 UTC, ckadner commented on dashboard/origin-mlx/README.md
> +Once the clusters have been deployed, they will need to be redeployed for UI work.
this may be slightly misleading. A more precise phrasing would be:

> Once the cluster has been deployed, the MLX UI will need to be redeployed after changes to the UI code have been made.

2022-04-08 23:43 UTC, ckadner commented on dashboard/origin-mlx/README.md
> +Change the image in /manifests/base/mlx-deployments/mlx-ui.yaml under the container with the name mlx-ui at spec.template.spec.containers
did you try this out? should this be either or? ... either 
- `./dashboard/origin-mlx/mlx-ui.yml` or 
- `/manifests/base/mlx-deployments/mlx-ui.yaml`

2022-04-08 23:43 UTC, ckadner commented on dashboard/origin-mlx/README.md
> +The Docker Compose stack can be brought up and taken down by running the following commands. The ```--project-name``` tag takes in the following argument as the name of the docker compose stack, whic
single back ticks ` `` ` for inline code sections like
> The `--project-name` flag ...

the benefit of using the `--project-name` flag is to keep the docker compose network and the volumes (stored assets) separate from the quickstart for development. Each docker compose project has separate network and volumes

2022-04-08 23:43 UTC, ckadner commented on dashboard/origin-mlx/README.md
> +### Terminal 2 - Start the MLX UI locally with Docker API
there is no Docker involved in this second terminal

2022-04-08 23:43 UTC, ckadner commented on dashboard/origin-mlx/README.md
> +For information on UI code structure, design principles, etc. check out the [MLX Developer Guide](developer-guide.md).
"MLX **_UI_** Developer Guide"  ... the API has a separate one

2022-04-08 23:43 UTC, ckadner commented on dashboard/origin-mlx/developer-guide.md
> +For more information on UI Development Setup go [here](README.md)
if we have two files

- the `/dashboard/origin-mlx/README.md` and 
- the `/dashboard/origin-mlx/developer-guide.md`

then we should make a clear separation of content:
- all the parts in the README.md that talk about development should be in the developer-guide, 
- and the README only has information about how to use (and deploy) the MLX UI

Although the developer guide also needs to inform about how to redeploy the MLX UI. So I am not convinced we need two documents if the README can contain all of it. If we have one README, then it should flow from overview, architecture diagram, how to deploy (point to general deployment docs) to running locally to development with docker compose, rebuild Docker image, push it, redeploy just the new MLX UI image to existing cluster, ...

2022-04-08 23:45 UTC, ckadner commented
the DCO check is failing since some commits are missing the `Signed-off-by: `

2022-04-22 19:44 UTC, closed without merging

2022-04-22 19:46 UTC, ckadner reviewed
/lgtm

Thanks Rithik I made a few final updates and merged it directly.