Add login for mlx-ui
machine-learning-exchange/mlx pull request #41
Opened 2021-05-18 17:52 UTC by yhwang

Add authentication in `/login` path. Use basic auth and simple
user model from a configuration in local file system. After a
successfull login, a cookie will be set in the browser and the user
info will be store in server. Currently, memorystore is used to
store session information. we can move it to persistent storage
later.

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

2021-05-18 18:20 UTC, Tomcli commented on dashboard/origin-mlx/server/server.ts
> -app.use('/', staticHandler);
are you able to reroute this with istio ingress without the static handler?

2021-05-18 18:29 UTC, yhwang commented on dashboard/origin-mlx/server/server.ts
> -app.use('/', staticHandler);
the mlx-ui virtualservice is using `/os` for mlx-ui svc. I don't know why we need this. so I removed it

2021-05-18 18:31 UTC, yhwang commented on dashboard/origin-mlx/server/server.ts
> -app.use('/', staticHandler);
are you saying there is no virtualservice in openshift deployment?

2021-05-18 18:35 UTC, ckadner requested changes

2021-05-18 18:35 UTC, ckadner commented on dashboard/origin-mlx/server/server.ts
> +    secret: 'machine learning exchange',
**Code Scan Warning:**
> Including unencrypted hard-coded authentication credentials in source code is dangerous because the credentials may be easily discovered. For example, the code may be open source, or it may be leaked or accidentally revealed, making the credentials visible to an attacker. This, in turn, might enable them to gain unauthorized access, or to obtain privileged information.

**Recommendation**

> Remove hard-coded credentials, such as user names, passwords and certificates, from source code. Instead, place them in configuration files, environment variables or other data stores if necessary. If possible, store configuration files including credential data separately from the source code, in a secure location with restricted access.

2021-05-18 18:37 UTC, yhwang commented on dashboard/origin-mlx/server/server.ts
> +    secret: 'machine learning exchange',
sure, let's get it from ENV

2021-05-18 18:39 UTC, Tomcli commented on dashboard/origin-mlx/server/server.ts
> -app.use('/', staticHandler);
I remember we need this because somehow when using virtualservice, the subpath won't route correctly without those static Handler. Not sure did it fix in node 14 or not.

2021-05-18 18:49 UTC, yhwang commented on dashboard/origin-mlx/server/server.ts
> +    secret: 'machine learning exchange',
fixed, read it from ENV or generate one on the fly.

2021-05-18 18:53 UTC, yhwang commented on dashboard/origin-mlx/server/server.ts
> -app.use('/', staticHandler);
interesting. I can put it back. if we have uncertainty.
FYI, I also changed the default value of `REACT_APP_BASE_PATH` to '' in server.ts. If no `REACT_APP_BASE_PATH` env, it will serve the `/`

2021-05-18 20:14 UTC, yhwang commented on dashboard/origin-mlx/server/server.ts
> -app.use('/', staticHandler);
I added those routes back with a condition check.

2021-05-21 19:57 UTC, ckadner commented
LGTM

@drewbutlerbb4 @Tomcli -- are we okay to merge this?

2021-05-21 20:13 UTC, Tomcli commented
@yhwang did this PR included the changes you have from yesterday?

2021-05-21 20:48 UTC, yhwang commented
@Tomcli this PR is for serving basic authentication in `<base path>/login`. for basic authentication, it enables the session and cookie.

2021-05-21 21:35 UTC, drewbutlerbb4 commented
lgtm

2021-05-21 21:47 UTC, merged